name: tfrun
description: Manage terraform collaboration
author: Digger

runs:
  using: "composite"
  steps:
    - run: |
        ls -la ${{github.action_path}}
        go run ${{github.action_path}}
      shell: bash
    - run: tfrun
      shell: bash

branding:
  icon: globe
  color: purple