name: tfrun
description: Manage terraform collaboration
author: Digger

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{github.action_path}}
        go build -o tfrun
        ./tfrun
      shell: bash

branding:
  icon: globe
  color: purple