name: tfrun
description: Manage terraform collaboration
author: Digger

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{github.action_path}}
        go run main.go ${{github.workspace}} plan
      shell: bash

branding:
  icon: globe
  color: purple